[package]
name = "parsink"
version = "0.1.0"
description = "Parsing with weights"
authors = ["Jamey Sharp <jamey@minilop.net>"]
repository = "https://github.com/jameysharp/parsink"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
